Repository googleapis/java-api-gateway, pull requests merged in 2021-05, with the labels that each got.

#32 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: apigateway, automerge, cla: yes, context: none

#33 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: apigateway, automerge, cla: yes

#34 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: apigateway, automerge, cla: yes, context: full

#36 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: apigateway, automerge, cla: yes, context: full

#40 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: apigateway, automerge, cla: yes, context: full

#41 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: apigateway, automerge, cla: yes

#46 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: apigateway, automerge, cla: yes, context: full

#51 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: apigateway, automerge, cla: yes
