Repository googleapis/java-api-gateway, pull requests merged in 2021-04, with the labels that each got.

#3 chore: remove readme generation code from synth.py
  synth.py
Labels: api: apigateway, automerge, cla: yes

#5 chore: start tracking obsolete files
  .kokoro/build.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: apigateway, automerge, cla: yes, context: none

#6 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: apigateway, automerge, cla: yes, context: full

#15 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: api: apigateway, automerge, cla: yes, context: full

#18 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: apigateway, automerge, cla: yes, context: full

#19 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: apigateway, automerge, cla: yes

#30 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: apigateway, automerge, cla: yes
